urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from iflex.workout.models import Workout
from iflex.members.models import Member
from iflex.exercises.models import ExerciseType

admin.autodiscover()

all_members_dict = {
    'queryset': Member.objects.all(),
}

#recent_workouts_dict = { 
#    'queryset': Workout.objects.all(),
#    'date_field': 'date',
#    'num_latest': 10,
#}

urlpatterns = patterns('',
                       # Workout
                       (r'^$', 'iflex.static.views.default'),

                       (r'^login/$', 'iflex.static.views.login'),

                       (r'^auth/$', 'iflex.static.views.auth'),

                       (r'^mockup/$', 'iflex.workout.views.'),

                       (r'^fetch/$', 'iflex.workout.views.fetch'),

                       (r'^workout/add/(?P<member_id>\d+)/$',
                        'iflex.workout.views.add'),

#                       (r'^workout/add_workout/(?P<member_id>\d+)/$',
#                        'iflex.workout.views.add_workout'),

                       (r'^workout/add_workout/$',
                        'iflex.workout.views.add_workout'),

#                       (r'^workout/fetch_workout_template/(?P<member_id>\d+)/$',
#                        'iflex.workout.views.fetch_workout_template'),

                       (r'^workout/profile/(?P<member_id>\d+)/$',
                        'iflex.workout.views.profile'),

                       (r'^workout/recent/(?P<member_id>\d+)/$',
                        'iflex.workout.views.recent'),

                       (r'^workout/details/(?P<member_id>\d+)/(?P<workout_id>\d+)/$',
                        'iflex.workout.views.details'),

                       # Exercises
                       (r'^exercises/$',
                        'iflex.exercises.views.default'),

                       (r'^exercises/add/$', 
                        'iflex.exercises.views.add'),

#                       (r'^exercises/addForm/$', 
#                        'iflex.exercises.views.addForm'),

#                       (r'^exercises/list/$', 
#                        'iflex.exercises.views.list'),

                       (r'^exercises/delete/(?P<exercise_id>\d+)/$', 
                        'iflex.exercises.views.delete'),

#                       (r'^exercises/script_init_workout_types/$',
#                        'iflex.exercises.views.script_init_workout_types'),

                       # Muscles
                       (r'^muscles/$',
                        'iflex.muscles.views.default'),

#                        (r'^muscles/default_muscle/$',
#                         'iflex.muscles.views.default_muscle'),

#                        (r'^muscles/default_muscle_group/$',
#                         'iflex.muscles.views.default_muscle_group'),

                        (r'^muscles/add/$', 
                         'iflex.muscles.views.add'),

#                        (r'^muscles/add_muscle_group/$', 
#                         'iflex.muscles.views.add_muscle_group'),

                        (r'^muscles/delete/(?P<muscle_id>\d+)/$', 
                         'iflex.muscles.views.delete'),

#                        (r'^muscles/delete_muscle_group/(?P<muscle_group_id>\d+)/$', 
#                         'iflex.muscles.views.delete_muscle_group'),

                       # Members
                       (r'^members/$', 'iflex.members.views.index'),

                       (r'^members/add/$', 'iflex.members.views.add'),

                       # Journal
                       (r'^journal/(?P<member_id>\d+)/$', 'iflex.journal.views.index'),

                       (r'^journal/$', 'iflex.journal.views.default'),

                       (r'^journal/add/(?P<member_id>\d+)/$', 'iflex.journal.views.add'),
#                       (r'^journal/add/$', 'iflex.journal.views.add'),

                       (r'^journal/addf/(?P<member_id>\d+)/$', 'iflex.journal.views.add'),

                       (r'^journal/delete/(?P<member_id>\d+)/(?P<journal_entry_id>\d+)/$',
                        'iflex.journal.views.delete'),

                       # Templates
                       # TODO: Should I even require a member id as an author or should I allow anonymous template creation
                       # using the session ID and IP (with some kind of spam restriction?)
                       (r'^template_editor/(?P<member_id>\d+)/$', 'iflex.template_editor.views.index'),

                       (r'^template_editor/save/(?P<member_id>\d+)/$', 'iflex.template_editor.views.save'),
                       
                       (r'^template_editor/load/$', 'iflex.template_editor.views.load'),
#                       (r'^template_editor/save/$', 'iflex.template_editor.views.save'),

                       # NOTE: using the naming convention "fetch" becaues it's remote...? instead of a data structure
#                       (r'^template_editor/fetch_exercises/$', 'iflex.template_editor.views.fetch_exercises'),
                       (r'^template_editor/init/$', 'iflex.template_editor.views.init'),

                       (r'^template_editor/service_load_exercise_templates/$', 'iflex.template_editor.views.service_load_exercise_templates'),
                       (r'^template_editor/service_load_lift_templates/$', 'iflex.template_editor.views.service_load_lift_templates'),
                       (r'^template_editor/service_load_workout_template/$', 'iflex.template_editor.views.service_load_workout_template'),

                       # Admin
                       (r'^admin/(.*)', admin.site.root),
#                       (r'^admin/', include('django.contrib.admin.urls')),

                       (r'^test/(?P<member_id>\d+)/$', 'iflex.workout.views.test'),


                       # Static Content (images, CSS, video, etc.)
#                       (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/abossy/projects/fitness/media', 'show_indexes': True}),

)

# The following conditional block is to test the JSON being passed through in the calls to "template_editor/init"
if settings.DEBUG:
    urlpatterns += patterns ('',
                             (r'^template_editor/view_save_form/$', 'iflex.template_editor.views.view_save_form'),
                             (r'^template_editor/view_exercise_list/$', 'iflex.template_editor.views.view_exercise_list'),
#                             (r'^template_editor/view_workout_template_list/(?P<collection_id>\d+)/$', 'iflex.template_editor.views.view_workout_template_list'),
                             (r'^template_editor/view_workout_template_list/$', 'iflex.template_editor.views.view_workout_template_list'),
                             (r'^template_editor/view_serialized_form/$', 'iflex.template_editor.views.view_serialized_form'),
                             (r'^template_editor/view_load/$', 'iflex.template_editor.views.view_load'),
                             )


if settings.DEBUG:
    urlpatterns += patterns ('',
                             (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                             )

if settings.DEBUG:
    urlpatterns += patterns ('',
                             (r'^admin_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.SITE_ROOT + settings.ADMIN_MEDIA_PREFIX, 'show_indexes': True}),
                             )

#if settings.DEBUG:
#    urlpatterns += patterns ('',
                             # Static Content (images, CSS, video, etc.)
#                             (r'^media/(?P<path>.*)$', 'django.views.static.serve',
#                              {'document_root': '/home/abossy/projects/fitness/media',
#                               'show_indexes': True
#                               }),
#                             )


 

journal/models.py
import os
import tempfile 

from django.db import models
from django.core.files.storage import FileSystemStorage

from iflex.members.models import Member

IMAGES_ROOT = 'images'

#FS = FileSystemStorage(location='/media/' + IMAGES_ROOT)

class JournalEntry (models.Model):

    member = models.ForeignKey(Member)

    notes = models.CharField(max_length=256)

    date = models.DateTimeField()

    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (str(self.id) + ', ' + str(self.member.id) + ', ' +
                self.notes + ', ' + str(self.date) + ', ' + str(self.time_created))

class Pic (models.Model):

    journal_entry = models.ForeignKey(JournalEntry)

    # TODO: Change 'file_name' to pic
    # TODO: Rename files based on unique id
    try:
        # If PIL is available, try testing PIL.
        # Checking for the existence of Image is enough for CPython, but
        # for PyPy, you need to check for the underlying modules
        # If PIL is not available, this test is equivalent to TextFile above.
        from PIL import Image, _imaging
        image = models.ImageField(upload_to='images/%Y/%m/%d')
    except ImportError:
        image = models.FileField(upload_to='images/%Y/%m/%d')
#    image_field = models.ImageField(upload_to=IMAGES_ROOT) #, storage=FS) #'photos/%Y/%m/%d')

    def __unicode__(self):
        return (str(self.id) + ', ' + str(self.journal_entry) + ', url = ' + self.image.url + ', path = ' + self.image.path)

journal/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect

from time import gmtime, strptime
from datetime import datetime

from iflex.journal.models import *
from iflex.members.models import Member

from django.forms import ModelForm
from django.core.files.uploadedfile import SimpleUploadedFile

class JournalForm (ModelForm):
    class Meta:
        model = Pic # JournalEntry
#        exclude = ('member',)

def default (request):
    return HttpResponseRedirect('/journal/1/')

def index (request, member_id):
    # TO DO: If member_id does not exist, then throw error page saying "Member does not exist."
    obj_dict = {
        'journal_entries_list': JournalEntry.objects.filter(member=member_id).order_by('-date')[0:10],
        'member': Member.objects.get(id=member_id),
        }
    return render_to_response('journal/index.html', obj_dict)

# TODO: Check for image extensions (.jpg, .gif, .png, etc.) (Download PIL [Python imaging library])
# TODO: Auto-create thumbnails
# TODO: Find a way to make the lack of a date throw a custom error message.
# TODO: Add date picker to date form field.
# TODO: Make the default date today's date.

def add (request, member_id):
    # validate form, yadda yadda
    # TO DO: extend this form by using a template. allow
    # the template to dynamically add multiple pics. auto-
    # matically bind the form to its respective model.
    if request.POST:
        jform = JournalForm(request.POST, request.FILES)
        if jform.is_valid():
            cd = jform.cleaned_data
            instance = jform.save() #cd.save()
            feedback = 'Note added successfully.'
            return HttpResponseRedirect('/journal/add/%s/?feedback=%s' % (member_id, feedback))
        else:
            obj_dict = {
                'journal_form': jform,
                'member': Member.objects.get(id=member_id),
            }
            return render_to_response('journal/add.html', obj_dict)
    else:
        obj_dict = {
            'journal_form': JournalForm(),
            'member': Member.objects.get(id=member_id),
            }
        if request.GET:
            obj_dict['feedback'] = request.GET['feedback']
        return render_to_response('journal/add.html', obj_dict)
 
# TODO: Delete images?
def delete (request, member_id, journal_entry_id):
    journal_entry = JournalEntry.objects.get (member=member_id, id=journal_entry_id)
    journal_entry.pic_set.all().delete()
    feedback = "Entry deleted successfully."
    journal_entry.delete()
    return HttpResponseRedirect('/journal/%s/?feedback=%s' % (member_id, feedback))

templates/journal/add.html
<html>

<head>
  <title>Add a Journal Entry</title>
  <link type="text/css" rel="stylesheet" href="/media/css/global.css" />
  <style type-"text/css">
    .item_container {
      clear: both;
      background-color: #0f0; /* green */
    }

    .labels_container {
      background-color: #f0f; /* purple */
      float: left;
      width: 96px;
      padding: 8px;
    }

    .text_boxes_container {
      background-color: #0ff; /* turqoise */
      float: right;
      width: 384px;
      padding: 8px;
    }

    .errors_container {
      padding: 8px;
    }

    .errors_container ul {
      margin: 0;
      padding: 0;
      list-style: none;
    }

    /* need to inherit width and float from text_boxes
       container, but also need to make it unique for
       addPictureEntry javascript function. */
    #pics_container { 
      background-color: #000; /* black */
      float: right;
      padding: 8px;
    }

    .pic_file_upload_element {
      clear: both;
    }

    #add_picture {
      float: right;
      clear: both;
    }

    .clear {
      clear: both;
    }
  </style>
  <script type="text/javascript">
    function addPictureEntry () {
        /* TODO: Create a valid way of retaining current file values when user adds new
                 uploadboxes using DOM. */
        var pics_container = document.getElementById('pics_container');

        var div_node = document.createElement('div');
        div_node.className = "pic_file_upload_element";

        var id_pic = document.createElement('input');
        id_pic.type = "file";
        id_pic.className = "pic";
        id_pic.id = "id_pic";

        pics_container.appendChild (div_node);

        pics_container.style.backgroundColor = "#faf";

    }
  </script>
</head>

<body>

{% if feedback %}
  <p>{{ feedback }}</p>
{% endif %}

<div id="wrap">
{% if journal_form %}

  <form action="/journal/add/{{ member.id }}/" method="post" enctype="multipart/form-data">

  <table border="0" cellpadding="4">
    {{ journal_form.as_table }}
  </table>

<!--  <input type="hidden" name="member" id="id_member" value="{{ member.id }}" /> -->

  <input type="Submit" value="Go!" />
  </form>

{% else %}

  <p>Some kind of problem occurred. Check journal_form for populated data.</p>

{% endif %}

<p><a href="/journal/{{ member.id }}/">Back to journal entries.</a></p>

</div>

</body>
</html>

templates/journal/index.html
<html>

<head>
  <title>My Journal</title>
  <link type="text/css" rel="stylesheet" href="/media/css/global.css" />
  <style type="text/css">
    .container {
/*      background-color: #00f; */
      align: center;
      margin: 0 0 32px 0;
    }

    .pics_container {
/*      background-color: #0f0; /* green */
      float: left;
      width: 176px;
    }

    .pic {
/*      background-color: #f0f; /* purple */
      padding: 6px 6px 0 6px;
    }

    .entry_container {
/*      background-color: #f00; */
      float: right;
      width: 336px;
    }
    
    .date {
/*      background-color: #0ff; /* turqoise */
      border-bottom: 1px #000 solid;
      padding: 8px;
    }

    .notes {
/*      background-color: #ddd; /* grey */
      padding: 8px;
    }

    .actions_container {
      float: right;
    }

    .clear {
      clear: both;
    }

    img {
      border: 1px #000 solid;
    }

    h2 {
      padding: 8px;
      border-bottom: 2px #000 solid;
    }
  </style>
</head>

<body>

<div id="wrap">
{% if journal_entries_list %}
  <h2>Journal for {{ member.firstName }} {{ member.lastName }}</h2>
  <p>{{ feedback }}</p>
  {% for journal_entry in journal_entries_list %}
  <div class="container">
    <div class="pics_container">
	{% for pic in journal_entry.pic_set.all %}
	<div class="pic">
	    <!-- TODO: Also learn how to save to and access the datestamped folders -->

	      <a href="{{ pic.image.url }}">
		<!-- TODO: When thumbnails get auto-created, check for dimensions, and
		     don't actually set them here. Just use the ones created by the
		     thumbnail and assume they're correct. -->
		<img src="{{ pic.image.url }}" width="160" height="120" />
	      </a>
	      <br />

	</div>
	{% endfor %}
    </div>
    <div class="entry_container">
      <div class="date">{{ journal_entry.date }}</div>
      <div class="notes">{{ journal_entry.notes }}</div>
    </div>
    <div class="clear"></div>
    <div class="actions_container">
      <div class="delete_entry">
	<!-- TODO: Make X a javascript AJAX call with POST parameters to the id that
	     should be deleted along with the member id. Have the AJAX callback delete
	     that physical entry from the DOM the user sees on this page. -->
	<a href="/journal/delete/{{ member.id }}/{{ journal_entry.id }}/">X</a>
      </div>
    </div>
  </div>
  {% endfor %}
{% else %}
  <p>No journal entries found for this user.</p>
{% endif %}
<p><a href="/journal/add/{{ member.id }}/">Add a journal entry</a></p>

</div>

</body>
</html>