urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from iflex.workout.models import Workout
from iflex.members.models import Member
from iflex.exercises.models import ExerciseType

admin.autodiscover()

all_members_dict = {
    'queryset': Member.objects.all(),
}

#recent_workouts_dict = { 
#    'queryset': Workout.objects.all(),
#    'date_field': 'date',
#    'num_latest': 10,
#}

urlpatterns = patterns('',
                       # Workout
                       (r'^$', 'iflex.static.views.default'),

                       (r'^login/$', 'iflex.static.views.login'),

                       (r'^auth/$', 'iflex.static.views.auth'),

                       (r'^mockup/$', 'iflex.workout.views.'),

                       (r'^fetch/$', 'iflex.workout.views.fetch'),

                       (r'^workout/add/(?P<member_id>\d+)/$',
                        'iflex.workout.views.add'),

#                       (r'^workout/add_workout/(?P<member_id>\d+)/$',
#                        'iflex.workout.views.add_workout'),

                       (r'^workout/add_workout/$',
                        'iflex.workout.views.add_workout'),

#                       (r'^workout/fetch_workout_template/(?P<member_id>\d+)/$',
#                        'iflex.workout.views.fetch_workout_template'),

                       (r'^workout/profile/(?P<member_id>\d+)/$',
                        'iflex.workout.views.profile'),

                       (r'^workout/recent/(?P<member_id>\d+)/$',
                        'iflex.workout.views.recent'),

                       (r'^workout/details/(?P<member_id>\d+)/(?P<workout_id>\d+)/$',
                        'iflex.workout.views.details'),

                       # Exercises
                       (r'^exercises/$',
                        'iflex.exercises.views.default'),

                       (r'^exercises/add/$', 
                        'iflex.exercises.views.add'),

#                       (r'^exercises/addForm/$', 
#                        'iflex.exercises.views.addForm'),

#                       (r'^exercises/list/$', 
#                        'iflex.exercises.views.list'),

                       (r'^exercises/delete/(?P<exercise_id>\d+)/$', 
                        'iflex.exercises.views.delete'),

#                       (r'^exercises/script_init_workout_types/$',
#                        'iflex.exercises.views.script_init_workout_types'),

                       # Muscles
                       (r'^muscles/$',
                        'iflex.muscles.views.default'),

#                        (r'^muscles/default_muscle/$',
#                         'iflex.muscles.views.default_muscle'),

#                        (r'^muscles/default_muscle_group/$',
#                         'iflex.muscles.views.default_muscle_group'),

                        (r'^muscles/add/$', 
                         'iflex.muscles.views.add'),

#                        (r'^muscles/add_muscle_group/$', 
#                         'iflex.muscles.views.add_muscle_group'),

                        (r'^muscles/delete/(?P<muscle_id>\d+)/$', 
                         'iflex.muscles.views.delete'),

#                        (r'^muscles/delete_muscle_group/(?P<muscle_group_id>\d+)/$', 
#                         'iflex.muscles.views.delete_muscle_group'),

                       # Members
                       (r'^members/$', 'iflex.members.views.index'),

                       (r'^members/add/$', 'iflex.members.views.add'),

                       # Journal
                       (r'^journal/(?P<member_id>\d+)/$', 'iflex.journal.views.index'),

                       (r'^journal/$', 'iflex.journal.views.default'),

                       (r'^journal/add/(?P<member_id>\d+)/$', 'iflex.journal.views.add'),
#                       (r'^journal/add/$', 'iflex.journal.views.add'),

                       (r'^journal/addf/(?P<member_id>\d+)/$', 'iflex.journal.views.add'),

                       (r'^journal/delete/(?P<member_id>\d+)/(?P<journal_entry_id>\d+)/$',
                        'iflex.journal.views.delete'),

                       # Templates
                       # TODO: Should I even require a member id as an author or should I allow anonymous template creation
                       # using the session ID and IP (with some kind of spam restriction?)
                       (r'^template_editor/(?P<member_id>\d+)/$', 'iflex.template_editor.views.index'),

                       (r'^template_editor/save/(?P<member_id>\d+)/$', 'iflex.template_editor.views.save'),
                       
                       (r'^template_editor/load/$', 'iflex.template_editor.views.load'),
#                       (r'^template_editor/save/$', 'iflex.template_editor.views.save'),

                       # NOTE: using the naming convention "fetch" becaues it's remote...? instead of a data structure
#                       (r'^template_editor/fetch_exercises/$', 'iflex.template_editor.views.fetch_exercises'),
                       (r'^template_editor/init/$', 'iflex.template_editor.views.init'),

                       (r'^template_editor/service_load_exercise_templates/$', 'iflex.template_editor.views.service_load_exercise_templates'),
                       (r'^template_editor/service_load_lift_templates/$', 'iflex.template_editor.views.service_load_lift_templates'),
                       (r'^template_editor/service_load_workout_template/$', 'iflex.template_editor.views.service_load_workout_template'),

                       # Admin
                       (r'^admin/(.*)', admin.site.root),
#                       (r'^admin/', include('django.contrib.admin.urls')),

                       (r'^test/(?P<member_id>\d+)/$', 'iflex.workout.views.test'),


                       # Static Content (images, CSS, video, etc.)
#                       (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/abossy/projects/fitness/media', 'show_indexes': True}),

)

# The following conditional block is to test the JSON being passed through in the calls to "template_editor/init"
if settings.DEBUG:
    urlpatterns += patterns ('',
                             (r'^template_editor/view_save_form/$', 'iflex.template_editor.views.view_save_form'),
                             (r'^template_editor/view_exercise_list/$', 'iflex.template_editor.views.view_exercise_list'),
#                             (r'^template_editor/view_workout_template_list/(?P<collection_id>\d+)/$', 'iflex.template_editor.views.view_workout_template_list'),
                             (r'^template_editor/view_workout_template_list/$', 'iflex.template_editor.views.view_workout_template_list'),
                             (r'^template_editor/view_serialized_form/$', 'iflex.template_editor.views.view_serialized_form'),
                             (r'^template_editor/view_load/$', 'iflex.template_editor.views.view_load'),
                             )


if settings.DEBUG:
    urlpatterns += patterns ('',
                             (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                             )

if settings.DEBUG:
    urlpatterns += patterns ('',
                             (r'^admin_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.SITE_ROOT + settings.ADMIN_MEDIA_PREFIX, 'show_indexes': True}),
                             )

#if settings.DEBUG:
#    urlpatterns += patterns ('',
                             # Static Content (images, CSS, video, etc.)
#                             (r'^media/(?P<path>.*)$', 'django.views.static.serve',
#                              {'document_root': '/home/abossy/projects/fitness/media',
#                               'show_indexes': True
#                               }),
#                             )


 

template_editor/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import simplejson

from iflex.members.models import Member
from iflex.exercises.models import ExerciseType

class TemplateCollection(models.Model):

    # TODO: ignore fancy week range and all. Each template consists of only one workout right now.
    name = models.CharField(max_length=64)

    author = models.ForeignKey(Member)

    def __unicode__(self):
        return (self.name + ', ' + str(self.author))

# class WorkoutTemplateChoiceField(forms.ModelChoiceField):
#     def _get_choices(self):
#         # Technically, don't have to do this, but do so anyway to be the most
#         # compatible with parent's behavior.
#         if hasattr(self, "_choices"):
#             return self._choices
#         return WorkoutTemplateQuerySetIterator(self.queryset, self.empty_label,
#             self.cache_choices)
#     choices = property(_get_choices, forms.ModelChoiceField._set_choices)

class WorkoutTemplate(models.Model):
    
    name = models.CharField(max_length=64, verbose_name='Template Name')

    position = models.IntegerField()

    # name "Workout A", "Upper Body Circuit", "Shoulders and Lats"

    # position (for ordering)

    # Some kind of date repition information ripped from Google Calendar
    # TODO: Should be viewable on a calendar

    # One-to-many relationships between workouts and collections at the moment
    # Will possibly make this a ManyToMany relationship in the future
    collection = models.ForeignKey(TemplateCollection, verbose_name='My Collections', blank=True, null=True)

    description = models.CharField(max_length=1024, blank=True, null=True)
    
    author = models.ForeignKey(Member)

    def __unicode__(self):
        return (self.name + ', ' + str(self.collection) + ', ' + str(self.author))

class WorkoutTemplateForm(ModelForm):
#    collections = forms.WorkoutTemplateChoiceField(TemplateCollection.objects.all())
    class Meta:
        model = WorkoutTemplate
        exclude = 'position'

def serialize_form(form):
    fields = []
    dict = {}
    for field in form:
        field_dict = {
            'html': str(field),  
            'label': field.label,
            'label_tag': field.label_tag(),
            'html_name': field.html_name,
            'help_text': field.help_text,
            'errors': field.errors,
        }
        dict.update( { field.name: field_dict } )
        fields.append(field.name)
    dict.update({ 'fields': fields })
    return dict

# An exercise that the member has actually completed as part of a workout
# NOTE: Holds mainly just ordering information
class ExerciseTemplate (models.Model): 

    workout_template = models.ForeignKey(WorkoutTemplate)

    # For ordering workout template correctly
    position = models.IntegerField()

    notes = models.CharField(max_length=128, blank=True, null=True)
    
    def __str__(self):
        return (str(self.id) + ', ' + str(self.workout_template) + ', ' + str(self.position) + '\n')

# Does this even need to exist?
class LiftTemplate (models.Model):

    workout_template = models.ForeignKey(WorkoutTemplate)

    # One-to-one
    exercise_template = models.ForeignKey(ExerciseTemplate)

    type = models.ForeignKey(ExerciseType)

    # TODO: Make ranges and other such semantics allowable? Question: what would these added
    # semantics allow us to do? Keep as strings for now.
    # TODO: We probably don't need a max length of 12. What will people actually put here?
#    warmup_sets = models.CharField(max_length=12)

#    warmup_reps = models.CharField(max_length=12)

#    workout_sets = models.CharField(max_length=12)

#    workout_reps = models.CharField(max_length=12)

#    tempo = models.CharField(max_length=12)

    rest = models.CharField(max_length=12)
    
#    notes = models.CharField(max_length=64, blank=True, null=True)

    def __unicode__(self):
        return (str(self.id) + ',' + str(self.type) + ',' + self.rest)

class RepsTemplate (models.Model):
    
    lift_template = models.ForeignKey(LiftTemplate)
    
    reps = models.CharField(max_length=12)

    # True if work, false if warmup
    work = models.BooleanField()
    
    def __unicode__(self):
        return (str(self.id) + ',' + self.reps + ',' + str(self.work))
#    def __str__(self):
#        return (str(self.id) + ', ' + str(self.workout_template) + ', ' + str(self.exercise_template) + ', ' + str(self.type) + ', ' + self.warmup_sets + ', ' + self.warmup_reps + ', ' + self.workout_sets + ', ' + self.workout_reps + ', ' + self.tempo + ', ' + self.rest)

# TODO: CardioTemplate

templates/template_editor/builder.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!-- The HTML 4.01 Transitional DOCTYPE declaration-->
<!-- above set at the top of the file will set     -->
<!-- the browser's rendering engine into           -->
<!-- "Quirks Mode". Replacing this declaration     -->
<!-- with a "Standards Mode" doctype is supported, -->
<!-- but may lead to some differences in layout.   -->

<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <!--                                           -->
    <!-- Any title is fine                         -->
    <!--                                           -->
    <title>fitnessUI</title>
    
    <!--                                           -->
    <!-- This script loads your compiled module.   -->
    <!-- If you add any GWT meta tags, they must   -->
    <!-- be added before this line.                -->
    <!--                                           -->
    <script type="text/javascript" language="javascript" src="/media/com.healthySoftware.fitnessUI/com.healthySoftware.fitnessUI.nocache.js"></script>
  </head>

  <!--                                           -->
  <!-- The body can have arbitrary html, or      -->
  <!-- you can leave the body empty if you want  -->
  <!-- to create a completely dynamic UI.        -->
  <!--                                           -->
  <body>

    <!-- OPTIONAL: include this if you want history support -->
    <iframe src="javascript:''" id="__gwt_historyFrame" tabIndex='-1' style="position:absolute;width:0;height:0;border:0"></iframe>

  </body>
</html>

templates/template_editor/workout_template_form.html
<table border="0" cellpadding="4">
  {{ workout_template_form.as_p }}
<!--
  <tr>
    <th>
      {{ workout_template_form.name.label_tag }}
    </th>
    <td>
      {{ workout_template_form.name }}
    </td>
  </tr>
  <tr>
    <th>
      {{ workout_template_form.position.label_tag }}
    </th>
    <td>
      {{ workout_template_form.position }}
    </td>
  </tr>
  <tr>
    <th>
      {{ workout_template_form.collection.label_tag }}
    </th>
    <td>
      <select name="collection" id="id_collection">
	<option value="" selected="selected">---------</option>
	<option value="1">1, &quot;Book of Muscle&quot; Workout, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="2">2, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="3">3, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="4">4, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="5">5, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="6">6, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="7">7, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="8">8, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="9">9, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="10">10, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="11">11, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
	<option value="12">12, Placeholder, 1, Adam, Bossy, 21, 73, 165</option>
      </select>
    </td>
  </tr>
-->
</table>

templates/template_editor/workout_template_list.html
<table border="0" cellpadding="4">
  <tr>
    <th>
      After: 
    </th>
    <td>
      <select name="collection" id="id_collection">
		<option value="" selected="selected">---------</option>
		{% for workout_template in workout_template_list %}
			<option value="{{ workout_template.id }}">{{ workout_template.name}}</option>
		{% endfor %}
      </select>
    </td>
  </tr>

templates/template_editor/workout_template_save_form.html
<table border="0" cellpadding="4">
  {{ workout_template_form.as_table }}
</table>